# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [ published ]

permissions:
  # This permission is needed for private repositories.
  contents: read
  # IMPORTANT: this permission is mandatory for trusted publishing
  id-token: write

jobs:
  pypi_publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - uses: pdm-project/setup-pdm@v3
      - name: Install dependencies
        run: pdm install
      - name: Build package
        run: pdm build
      - name: Publish package
        env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: pdm publish
